'use client';
import {FormEvent,useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3001';
export default function Courses(){
 const [courses,setCourses]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[error,setError]=useState('');
 const token=()=>localStorage.getItem('phantom_token')||'';
 const h=()=>({Authorization:'Bearer '+token()});
 async function load(){const [c,u]=await Promise.all([fetch(API+'/api/courses',{headers:h()}),fetch(API+'/api/users',{headers:h()})]);if(c.status===401||c.status===403){location.href='/login';return;}setCourses(await c.json());setUsers(await u.json());}
 useEffect(()=>{load()},[]);
 async function createCourse(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch(API+'/api/courses',{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({title:f.get('title'),description:f.get('description'),mandatory:f.get('mandatory')==='on'})});if(!r.ok){setError('Ошибка создания курса');return;}e.currentTarget.reset();load();}
 async function publish(id:string){await fetch(API+'/api/courses/versions/'+id+'/publish',{method:'POST',headers:h()});load();}
 async function material(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch(API+'/api/courses/versions/'+id+'/materials',{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({title:f.get('title'),type:f.get('type'),content:f.get('content'),required:true})});if(r.ok){e.currentTarget.reset();load();}}
 async function assign(e:FormEvent<HTMLFormElement>,courseId:string){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch(API+'/api/assignments',{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify({userId:f.get('userId'),courseId,dueAt:f.get('dueAt')||undefined})});const x=await r.json();setError(r.ok?'Курс назначен':(x.message||'Ошибка назначения'));}
 return <main className="adminPage"><header><div><div className="brand">PHANTOM</div><h1>Учебные программы</h1></div><a href="/company">Сотрудники</a></header>{error&&<p className={error==='Курс назначен'?'notice':'error'}>{error}</p>}
 <section className="adminGrid"><form className="card compact" onSubmit={createCourse}><h2>Новый курс</h2><label>Название<input name="title" required/></label><label>Описание<textarea name="description"/></label><label className="check"><input name="mandatory" type="checkbox"/> Обязательное обучение</label><button>Создать черновик</button></form>
 <div className="panel"><h2>Курсы</h2>{courses.map(c=>{const v=c.versions[0];return <article className="courseAdmin" key={c.id}><div className="courseHead"><div><small>{c.mandatory?'Обязательный':'Дополнительный'} · версия {v?.version}</small><h3>{c.title}</h3><p>{c.description}</p></div><b>{v?.status}</b></div>{v?.status==='DRAFT'&&<><form className="inlineForm" onSubmit={e=>material(e,v.id)}><input name="title" placeholder="Название материала" required/><select name="type"><option value="TEXT">Текст</option><option value="VIDEO">Видео</option><option value="PDF">PDF</option><option value="IMAGE">Изображение</option></select><textarea name="content" placeholder="Текст или ссылка"/><button>Добавить материал</button></form><div className="materials">{v.materials.map((m:any)=><span key={m.id}>{m.type}: {m.title}</span>)}</div><button className="secondary" onClick={()=>publish(v.id)}>Опубликовать версию</button></>}
 {v?.status==='PUBLISHED'&&<form className="inlineForm assign" onSubmit={e=>assign(e,c.id)}><select name="userId" required><option value="">Выберите сотрудника</option>{users.map(u=><option key={u.id} value={u.id}>{u.lastName} {u.firstName}</option>)}</select><input name="dueAt" type="datetime-local"/><button>Назначить</button></form>}</article>})}</div></section></main>
}
