'use client';
import {FormEvent,useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3001';
export default function Groups(){
 const [groups,setGroups]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[deps,setDeps]=useState<any[]>([]),[error,setError]=useState('');
 const token=()=>localStorage.getItem('phantom_token')||'';const h=()=>({Authorization:'Bearer '+token()});
 async function load(){const [g,u,d]=await Promise.all([fetch(API+'/api/groups',{headers:h()}),fetch(API+'/api/users',{headers:h()}),fetch(API+'/api/departments',{headers:h()})]);if(g.status===401||g.status===403){location.href='/login';return;}setGroups(await g.json());setUsers(await u.json());setDeps(await d.json());}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body:any={name:f.get('name')};if(f.get('departmentId'))body.departmentId=f.get('departmentId');const r=await fetch(API+'/api/groups',{method:'POST',headers:{...h(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const x=await r.json();setError(x.message||'Ошибка создания группы');return;}e.currentTarget.reset();setError('');load();}
 async function add(groupId:string,userId:string){if(!userId)return;const r=await fetch(API+'/api/groups/'+groupId+'/members/'+userId,{method:'POST',headers:h()});if(r.ok)load();}
 async function remove(groupId:string,userId:string){const r=await fetch(API+'/api/groups/'+groupId+'/members/'+userId,{method:'DELETE',headers:h()});if(r.ok)load();}
 return <main className="adminPage"><header><div><div className="brand">PHANTOM</div><h1>Группы сотрудников</h1></div><a href="/company">← Администрирование</a></header>{error&&<p className="error">{error}</p>}<section className="adminGrid"><form className="card compact" onSubmit={create}><h2>Новая группа</h2><label>Название<input name="name" required minLength={2}/></label><label>Подразделение<select name="departmentId"><option value="">Без подразделения</option>{deps.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button>Создать группу</button></form><div className="panel"><h2>Группы</h2>{groups.map(g=><article className="card compact topGap" key={g.id}><h3>{g.name}</h3><small>{g.department?.name||'Без подразделения'}</small><label>Добавить сотрудника<select defaultValue="" onChange={e=>{add(g.id,e.target.value);e.currentTarget.value='';}}><option value="">Выберите сотрудника</option>{users.filter(u=>!g.members.some((m:any)=>m.user.id===u.id)).map(u=><option key={u.id} value={u.id}>{u.lastName} {u.firstName}</option>)}</select></label>{g.members.map((m:any)=><div className="org" key={m.user.id}><div><b>{m.user.lastName} {m.user.firstName}</b><small>{m.user.email}</small></div><button type="button" onClick={()=>remove(g.id,m.user.id)}>Убрать</button></div>)}</article>)}</div></section></main>
}
